version: '3'
services:
  db:
    build:
      context: .
      dockerfile: "mysql.Dockerfile"
    container_name: "mysql-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "qwerty"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
